// Generated by MistCSS, do not modify
import './Button.mist.css'

import type { JSX, ReactNode } from 'react'

type ButtonProps = {
  children?: ReactNode
  size?: 'lg' | 'sm'
  danger?: boolean
} & JSX.IntrinsicElements['button']

export function Button({ children, size, danger, ...props }: ButtonProps) {
  return (
    <button {...props} className="button" data-size={size} data-danger={danger}>
      {children}
    </button>
  )
}
